fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Entity\User
#  service:
#    user_manager: custom_user_manager_id
  from_email:
    address: "vincent@vfac.fr"
    sender_name: "vincent@vfac.fr"
